### ISSUE TITLE
Still doesn't work

### ISSUE THREAD

**Issue by xnmp** [JadenGeller/Guac#1]
```
ython 3.5.3 (a39af0be3a22, Jun 05 2017, 20:18:00)
[PyPy 5.8.0-beta0 with GCC 6.2.0 20160901] on linux
Type "help", "copyright", "credits" or "license" for more information.
And now for something completely different: ``why there is no "PyPy 1.4
released" in topic any more?''
>>>> guac.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'guac' is not defined
>>>> execfile("guac.py")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'execfile' is not defined
>>>> exec(open("guac.py").read(),globals())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 158, in <module>
  File "<string>", line 103, in monadic_context
  File "<string>", line 50, in _run
  File "<string>", line 48, in step
  File "<string>", line 129, in bind
  File "<string>", line 41, in proceed
  File "/home/user/pypy3/lib-python/3/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/user/pypy3/lib-python/3/copy.py", line 292, in _reconstruct
    y = callable(*args)
  File "/home/user/pypy3/lib-python/3/copyreg.py", line 88, in __newobj__
    return cls.__new__(cls, *args)
TypeError: object.__new__(generator) is not safe, use generator.__new__()
```

@JadenGeller I'm using pypy3.

**Comment by JadenGeller** [comment]
Did you try to install guac from `pip`?

```
pip3 install guac
```

Then you can simply write `import guac`.

**Comment by JadenGeller** [comment]
There's no file named `guac.py`, so I don't know what you're trying to do.

**Comment by JadenGeller** [comment]
Closing due to inactivity.
